language: python
python:
- 3.6
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  password:
    secure: bP1u3oojWCx6QF/Bjfwv5Vo0i11r1ik+M6sxXUhVty+qR25b0Sy0F+xcSOIeIiVIqdW633C6MRMepSEec8/eBBcov+hFuhy1+UBdra09RaIeSqpmFhMmGDgW+b6UXhU4ozSb/wsiBjF647F4dhhAbtawPn/L3hoZc3S9xBlYDGboceWfhln2aJ6wd8Ooqo6wJTXi4wCX+LABMHR1Wu/lZJ/mr6CHjXEPRKGagf5F4d5/B01Q6QazF1AHDAsnm84pKRrt+TFi8rdA33+9vwymuO0ioPU83BbyCZKq/titA4LewHlG4x/A73//L77qE9y718xpHDqwG4dQWBGF2PZWp8Lv3QM3Y9+2p/Yq0ANwTdhPkDR9o8cr4L5TX5NvJT4vuINxwYjOJoBVYMewewjkUywOS2AbulJqHnukfquMPt2slbIFqRNs824zStOrGz/7UzgUkZQ2C8I+PAj8SkqtBn+7AesDP/dLhnTy5vcAF6/6lg9PpR2xcpTQc8HiylKq7PsrF2FjV1SpFVDt5ia8w3a8S3ccqcmyb6SGC0RUQlGXNMcOtLxEYsBI87ft7HBy31s5RBZ15hy2qv3sEgzJ5JJkCF/Rr9c4pOXNWFMN2cBa7ySWp8i/r8cEpQm0/nlkPiF5MyqOcpnoAPQbGRGjVAkgEsGGHZ4oU0HWHF420IM=
  on:
    tags: true
    repo: MAIF/melusine
    python: 3.6
