language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  password:
    secure:
  on:
    tags: true
    repo: MAIF/melusine
    python: 3.6
